### ISSUE TITLE
java.lang.OutOfMemoryError on Android application

### ISSUE THREAD

**Issue by kode-git** [kode-git/privacy-aware-crowdsensing#10]
### App Error Stacktrace

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.crowdsensingapp, PID: 22132
    java.lang.OutOfMemoryError: Could not allocate JNI Env: Failed anonymous mmap(0x0, 8192, 0x3, 0x2, 61, 0): Permission denied. See process maps in the log.
        at java.lang.Thread.nativeCreate(Native Method)
        at java.lang.Thread.start(Thread.java:733)
        at com.android.volley.RequestQueue.start(RequestQueue.java:127)
        at com.android.volley.toolbox.Volley.newRequestQueue(Volley.java:91)
        at com.android.volley.toolbox.Volley.newRequestQueue(Volley.java:67)
        at com.android.volley.toolbox.Volley.newRequestQueue(Volley.java:102)
        at com.example.crowdsensingapp.MapsActivity.getMeanDb(MapsActivity.java:301)
        at com.example.crowdsensingapp.MapsActivity$5.onLocationResult(MapsActivity.java:228)
        at com.google.android.gms.internal.location.zzau.notifyListener(Unknown Source:4)
        at com.google.android.gms.common.api.internal.ListenerHolder.notifyListenerInternal(Unknown Source:17)
        at com.google.android.gms.common.api.internal.ListenerHolder$zaa.handleMessage(Unknown Source:5)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at com.google.android.gms.internal.base.zap.dispatchMessage(Unknown Source:8)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

### How to execute bug
Start applications and wait until the crash, it is caused by OutOfMemoryError for permissions to allocate JNI environment.

**Comment by kode-git** [comment]
Tested and solved by @andreagurioli1995
